// Setup script for the "Send a Trust Line Token" tutorial.
// Funds an issuer and holder wallet, enables Default Ripple on the issuer,
// and writes their seeds to setup.json for use by the main tutorial script.

package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/Peersyst/xrpl-go/pkg/crypto"
	"github.com/Peersyst/xrpl-go/xrpl/faucet"
	"github.com/Peersyst/xrpl-go/xrpl/rpc"
	transactions "github.com/Peersyst/xrpl-go/xrpl/transaction"
	"github.com/Peersyst/xrpl-go/xrpl/transaction/types"
	"github.com/Peersyst/xrpl-go/xrpl/wallet"
)

func main() {
	fmt.Print("Setting up tutorial: 0/2\r")

	cfg, err := rpc.NewClientConfig(
		"https://s.altnet.rippletest.net:51234/",
		rpc.WithFaucetProvider(faucet.NewTestnetFaucetProvider()),
	)
	if err != nil {
		panic(err)
	}
	client := rpc.NewClient(cfg)

	// Fund issuer and holder wallets from the Testnet faucet.
	issuer, err := wallet.New(crypto.ED25519())
	if err != nil {
		panic(err)
	}
	if err := client.FundWallet(&issuer); err != nil {
		panic(err)
	}
	holder, err := wallet.New(crypto.ED25519())
	if err != nil {
		panic(err)
	}
	if err := client.FundWallet(&holder); err != nil {
		panic(err)
	}

	fmt.Print("Setting up tutorial: 1/2\r")

	// Enable Default Ripple on the issuer so holders can transfer the issued
	// token between each other through the issuer's trust lines.
	accountSetTx := &transactions.AccountSet{
		BaseTx: transactions.BaseTx{
			Account: types.Address(issuer.ClassicAddress),
		},
	}
	accountSetTx.SetAsfDefaultRipple()

	flatTx := accountSetTx.Flatten()
	if err := client.Autofill(&flatTx); err != nil {
		panic(err)
	}
	txBlob, _, err := issuer.Sign(flatTx)
	if err != nil {
		panic(err)
	}
	accountSetResp, err := client.SubmitTxBlobAndWait(txBlob, false)
	if err != nil {
		panic(err)
	}
	if !accountSetResp.Validated {
		fmt.Println("Error: Unable to configure issuer.")
		os.Exit(1)
	}

	fmt.Print("Setting up tutorial: 2/2\r")

	// Write setup data to JSON file.
	setupData := struct {
		Description string `json:"description"`
		Issuer      any    `json:"issuer"`
		Holder      any    `json:"holder"`
	}{
		Description: "This file is auto-generated by the setup script. It stores XRPL account info for use in the Send a Trust Line Token tutorial.",
		Issuer: map[string]string{
			"address": string(issuer.ClassicAddress),
			"seed":    issuer.Seed,
		},
		Holder: map[string]string{
			"address": string(holder.ClassicAddress),
			"seed":    holder.Seed,
		},
	}

	jsonData, err := json.MarshalIndent(setupData, "", "  ")
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("setup.json", jsonData, 0644); err != nil {
		panic(err)
	}

	fmt.Println("Setting up tutorial: Complete!")
}
