// Setup script for the "Send a Trust Line Token" tutorial.
// Funds an issuer and holder wallet, enables Default Ripple on the issuer,
// and writes their seeds to setup.json for use by sendTrustLineToken.js.

import xrpl from 'xrpl'
import fs from 'fs'

process.stdout.write('Setting up tutorial: 0/2\r')

const client = new xrpl.Client('wss://s.altnet.rippletest.net:51233')
await client.connect()

// Fund issuer and holder wallets from the Testnet faucet.
const [
  { wallet: issuer },
  { wallet: holder }
] = await Promise.all([
  client.fundWallet(),
  client.fundWallet()
])

process.stdout.write('Setting up tutorial: 1/2\r')

// Enable Default Ripple on the issuer so holders can transfer the issued
// token between each other through the issuer's trust lines.
const accountSetResponse = await client.submitAndWait({
  TransactionType: 'AccountSet',
  Account: issuer.address,
  SetFlag: xrpl.AccountSetAsfFlags.asfDefaultRipple
}, { wallet: issuer, autofill: true })

if (accountSetResponse.result.meta.TransactionResult !== 'tesSUCCESS') {
  console.error('Error: Unable to configure issuer:', accountSetResponse.result.meta.TransactionResult)
  await client.disconnect()
  process.exit(1)
}

process.stdout.write('Setting up tutorial: 2/2\r')

// Write setup data to JSON file.
const setupData = {
  description: 'This file is auto-generated by setup.js. It stores XRPL account info for use in the Send a Trust Line Token tutorial.',
  issuer: {
    address: issuer.address,
    seed: issuer.seed
  },
  holder: {
    address: holder.address,
    seed: holder.seed
  }
}

fs.writeFileSync('setup.json', JSON.stringify(setupData, null, 2))

process.stdout.write('Setting up tutorial: Complete!\n')

await client.disconnect()
