# Setup script for the "Send a Trust Line Token" tutorial.
# Funds an issuer and holder wallet, enables Default Ripple on the issuer,
# and writes their seeds to setup.json for use by send_trust_line_token.py.

import json
import sys

from xrpl.clients import JsonRpcClient
from xrpl.models.transactions import AccountSet
from xrpl.models.transactions.account_set import AccountSetAsfFlag
from xrpl.transaction import submit_and_wait
from xrpl.wallet import generate_faucet_wallet

print("Setting up tutorial: 0/2", end="\r")

client = JsonRpcClient("https://s.altnet.rippletest.net:51234")

# Fund issuer and holder wallets from the Testnet faucet.
issuer = generate_faucet_wallet(client)
holder = generate_faucet_wallet(client)

print("Setting up tutorial: 1/2", end="\r")

# Enable Default Ripple on the issuer so holders can transfer the issued
# token between each other through the issuer's trust lines.
account_set_response = submit_and_wait(
    AccountSet(
        account=issuer.address,
        set_flag=AccountSetAsfFlag.ASF_DEFAULT_RIPPLE,
    ),
    client,
    issuer,
)

result_code = account_set_response.result["meta"]["TransactionResult"]
if result_code != "tesSUCCESS":
    print(f"Error: Unable to configure issuer: {result_code}")
    sys.exit(1)

print("Setting up tutorial: 2/2", end="\r")

# Write setup data to JSON file.
setup_data = {
    "description": "This file is auto-generated by setup.py. It stores XRPL account info for use in the Send a Trust Line Token tutorial.",
    "issuer": {
        "address": issuer.address,
        "seed": issuer.seed,
    },
    "holder": {
        "address": holder.address,
        "seed": holder.seed,
    },
}

with open("setup.json", "w") as f:
    json.dump(setup_data, f, indent=2)

print("Setting up tutorial: Complete!")
